version: "3"

services:
  # a postgres container for providing database access.
  postgres:
    image: sameersbn/postgresql:9.4-12
    environment:
      - PGPASSWORD=iKWMjsbqrbA!jqo
      - DB_USER=trashradar
      - DB_PASS=HS8J12MQW~975NS
      - DB_NAME=trashradar
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  # redis for caching and queueing.
  redis:
    image: redis:3-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  postgres-data:
