version: "3"

services:
  # a postgres container for providing database access.
  postgres:
    image: kartoza/postgis:9.5-2.2
    environment:
      - POSTGRES_USER=trashradar
      - POSTGRES_PASS=HS8J12MQW~975NS
      - POSTGRES_DBNAME=trashradar
      - ALLOW_IP_RANGE=0.0.0.0/0
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  # redis for caching and queueing.
  redis:
    image: redis:3-alpine
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  postgres-data:
